### ISSUE TITLE
startup validation issue

### ISSUE THREAD

**Issue by omeryounus** [AuthySE/Authy-demo#1]
Below is the error when loading the project.

ValidationFailedError: Validation Failed
    at validate (F:\Authy-demo2\node_modules\authy-client\dist\src\validator.js:74:11)
    at new Client (F:\Authy-demo2\node_modules\authy-client\dist\src\client.js:92:29)
    at Object.<anonymous> (F:\Authy-demo2\server\controllers\users.js:11:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    ......

**Comment by josh-authy** [comment]
Hi @omeryounus,

This error is caused because the Authy API key is not part of your environment.  Specifically, the value referenced here:
https://github.com/AuthySE/Authy-demo/blob/master/server/controllers/users.js#L7

You'll need to add the key here, https://github.com/AuthySE/Authy-demo/blob/master/demo.env and then `source demo.env` from your command line before starting the app.   

I'm going to change the startup script to check for this value and provide a more informative error.  Thank you for letting us know!

Cheers,
- Josh @ Authy

**Comment by josh-authy** [comment]
@omeryounus If you're using Windows, you may need to set the environmental variables via PowerShell.  Here is a StackOverflow showing how to do this with Windows:
http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows

**Comment by omeryounus** [comment]
Yes, It would be better to have script which detect OS on start and set the path accordingly.

**Comment by omeryounus** [comment]
Yes, thanks I will post it there.
